---
# tasks file for CloudManager

- name: Install "Inline with Upstream Stable"
  yum:
    name: "https://centos7.iuscommunity.org/ius-release.rpm"

- name: Install python3
  yum:
    name: python36u

- name: Install pip
  yum:
    name: python36u-pip

- name: Install python-tools
  yum:
    name: python-tools

- name: Install Ansible
  pip:
    name: ansible
    executable: pip3.6

- name: Install Git
  yum:
    name: git

- name: Clone Contrail python api
  git:
    repo:    'https://github.com/Juniper/contrail-python-api.git'
    dest:    /opt/contrail-python-api

- name: Convert Contrail python api to Python3
  command: 2to3 contrail-python-api
  args:
    chdir: /opt

- name: Install Contrail python api
  command: python setup.py install
  args:
    chdir: /opt/contrail-python-api

- name: Add contrail virtual network module to Ansible
  copy:
    src:  '{{ role_path }}/files/modules/contrail_virtual_network.yaml'
    dest: /etc/foo.conf
